=== domasd/UniversityApps/Interneto technologijos/IT/XML atsiskaitymui/XSD/XMLSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace='http://dziaugys.com/orouostai' xmlns:p='http://dziaugys.com/orouostai' elementFormDefault="qualified">

  <xs:annotation>
    <xs:documentation>
      Ši xml schema yra skirta tikrinti skrydžių xml teisingumą ir korektiškumą.
    </xs:documentation>
  </xs:annotation>

  <xs:element name="OroUostai" type="p:OroUostaiTipas">
    <!--8 reikalavimas-->
    
    <xs:key name="OroUostoRaktas">
      <xs:selector xpath="p:OroUostas"/>
      <xs:field xpath="@kodas"/>
    </xs:key>
    
    <xs:keyref name="NuorodaIOroUosta" refer="p:OroUostoRaktas">
      <xs:selector xpath="p:OroUostas/p:skrydis/p:tikslas"/>
      <xs:field xpath="@kodas"/>
    </xs:keyref>
    
  </xs:element>


  <xs:complexType name="OroUostaiTipas">
    <xs:sequence>
      <xs:element name="OroUostas" type="p:OroUostasTipas" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="OroUostasTipas">
    <xs:sequence>
      <xs:element name="skrydis" type="p:skrydisTipas" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="p:oroUostasAttributes"/>
  </xs:complexType>

  <xs:complexType name="skrydisTipas">
    <xs:all minOccurs="1">
      <xs:element name="bendrove" type="xs:string"/>
      <xs:element name="tikslas">
        <xs:complexType>
          <xs:attributeGroup ref="p:oroUostasAttributes"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="kaina" type="p:kainaTipas"/>
      <xs:element name="lektuvas" type="p:lektuvasTipas"/>
      <xs:element name="data" type="p:skrydzioLaikasDataSuDienuSkTipas"/>
      <xs:element name="laikas" type="p:skrydzioLaikasValandosTipas"/>
      <xs:element name="trukme" type="xs:integer"/>
      <xs:element name="kalbos" minOccurs="0">
        <!--2 reikalavimas-->
        <xs:simpleType>
          <xs:list itemType='xs:language'/>
        </xs:simpleType>
      </xs:element>

    </xs:all>
  </xs:complexType>

  <!--4 reikalavimas-->
  <xs:complexType name='skrydzioLaikasTipas' mixed='true'>
    <xs:sequence minOccurs='1'>
      <xs:element name='pakilimo' type='xs:string'/>
      <xs:element name='nusileidimo' type='xs:string'/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name='skrydzioLaikasDataTipas' mixed='false'>
    <xs:complexContent>
      <xs:restriction base='p:skrydzioLaikasTipas'>
        <xs:sequence>
          <xs:element name='pakilimo'>
            <xs:simpleType>
              <xs:restriction base='xs:string'>
                <xs:pattern value='[0-9]{4}-[0-9]{2}-[0-9]{2}'/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name='nusileidimo'>
            <xs:simpleType>
              <xs:restriction base='xs:string'>
                <xs:pattern value='[0-9]{4}-[0-9]{2}-[0-9]{2}'/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <!--6 reikalavimas-->
  <xs:complexType name='skrydzioLaikasValandosTipas' mixed='true'>
    <xs:complexContent>
      <xs:restriction base='p:skrydzioLaikasTipas'>
        <xs:sequence>
          <xs:element name='pakilimo'>
            <xs:simpleType>
              <xs:restriction base='xs:string'>
                <xs:pattern value='[0-9]{2}:[0-9]{2}'/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name='nusileidimo'>
            <xs:simpleType>
              <xs:restriction base='xs:string'>
                <xs:pattern value='[0-9]{2}:[0-9]{2}'/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name='skrydzioLaikasDataSuDienuSkTipas' mixed='false'>
    <xs:complexContent>
      <xs:extension base='p:skrydzioLaikasDataTipas'>
        <xs:attribute name='dienuSk' type='xs:integer' use='optional'/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>




  <!--3 reikalavimas-->
  <xs:simpleType name="galiaTipas">
    <xs:restriction base="xs:integer">
      <xs:minExclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="galiaSuMatVntTipas">
    <xs:simpleContent>
      <xs:extension base="p:galiaTipas">
        <xs:attribute name="matVnt" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="galieRealistiskaSuMatVntTipas">
    <xs:simpleContent>
      <xs:restriction base="p:galiaSuMatVntTipas">
        <xs:maxInclusive value="50000"/>
        <xs:fractionDigits value="0"/>
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="aptarvimasTipas">
    <xs:choice>
      <xs:element name="bendroveIrData">
        <xs:complexType>
          <xs:all>
            <xs:element name="bendrove" type="xs:string"/>
            <xs:element name="data" type="xs:date"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element name="bendrove" type="xs:string"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="lektuvasTipas">
    <xs:all>
      <xs:element name ="pavadinimas" type="xs:string"/>
      <xs:element name="galia" type="p:galieRealistiskaSuMatVntTipas"/>
      <!--7 reikalavimas-->
      <xs:element name="aptarnavimas" minOccurs="0" type="p:aptarvimasTipas"/>
    </xs:all>
    <xs:attribute name="vietos" type="xs:integer"/>
  </xs:complexType>

  <xs:complexType name="kainaTipas">
    <xs:all>
      <xs:element name="Eur" type="xs:decimal"/>
      <xs:element name="Lt" type="xs:decimal" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <!--1 reikalavimas-->
  <xs:simpleType name ="kodasTipas">
    <xs:restriction base ="xs:string">
      <xs:pattern value="[A-Z]{3}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:attributeGroup name="oroUostasAttributes">
    <xs:attribute name="pavadinimas" type="xs:string" use="required"/>
    <xs:attribute name="kodas" type="p:kodasTipas"  use="required"/>
  </xs:attributeGroup>

  <xs:attribute name="pavadinimas" type="xs:string"/>

</xs:schema>

=== domasd/UniversityApps/Interneto technologijos/IT/XML atsiskaitymui/XSD/Skrydziai.xml
<?xml version="1.0" encoding="utf-8" ?>
<OroUostai xmlns='http://dziaugys.com/orouostai' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchema.xsd">
  <OroUostas pavadinimas ="Vilniaus tarptautinis oro uostas" kodas = "VNO" >
    <skrydis>
      <bendrove>AIR BALTIC</bendrove>
      <tikslas pavadinimas="Kauno oro uostas" kodas = "KUN"/>
      <kaina>
        <Eur>100</Eur>
        <Lt>345.28</Lt>
      </kaina>
      <lektuvas>
        <pavadinimas>AIRBUS A200</pavadinimas>
        <galia matVnt="kW">8200</galia>
        <aptarnavimas>
          <bendroveIrData>
            <bendrove>VNO Aicraft maintenance</bendrove>
            <data>2015-10-02</data>
          </bendroveIrData>
        </aptarnavimas>
      </lektuvas>
      <data dienuSk="0">
        <pakilimo>2015-10-10</pakilimo>
        <nusileidimo>2015-10-10</nusileidimo>
      </data>
      <laikas>
        <pakilimo>11:40</pakilimo>
        <nusileidimo>12:10</nusileidimo>
        11:40-12:10
      </laikas>
      <trukme>30</trukme>
      <kalbos>lt-LT en-GB</kalbos>
    </skrydis>
    <skrydis>
      <bendrove>RYANAIR</bendrove>
      <tikslas pavadinimas="Copenhagen Airport" kodas = "CPH"/>
      <kaina>
        <Eur>18</Eur>
      </kaina>
      <lektuvas vietos="150">
        <pavadinimas> BOEING 737 </pavadinimas>
        <galia>8200</galia>
        <aptarnavimas>
          <bendrove>Independent repair</bendrove>
        </aptarnavimas>
      </lektuvas>
      <data>
        <pakilimo>2015-10-11</pakilimo>
        <nusileidimo>2015-10-11</nusileidimo>
      </data>
      <laikas>
        <pakilimo>11:00</pakilimo>
        <nusileidimo>12:00</nusileidimo>
      </laikas>
      <trukme>60</trukme>
    </skrydis>
    <skrydis>
      <bendrove>RYANAIR</bendrove>
      <tikslas pavadinimas="London Stansted Airport" kodas = "STD"/>
      <kaina>
        <Eur>30</Eur>
      </kaina>
      <lektuvas vietos="150">
        <pavadinimas> BOEING 737 </pavadinimas>
        <galia>7000</galia>
      </lektuvas>
      <data>
        <pakilimo>2015-10-09</pakilimo>
        <nusileidimo>2015-10-09</nusileidimo>
      </data>
      <laikas>
        <pakilimo>06:00</pakilimo>
        <nusileidimo>07:00</nusileidimo>
      </laikas>
      <trukme>60</trukme>
    </skrydis>
    <skrydis>
      <bendrove>Turkish airlines</bendrove>
      <tikslas pavadinimas="John F. Kennedy Airport" kodas = "JFK"/>
      <kaina>
        <Eur>700</Eur>
      </kaina>
      <lektuvas vietos="400">
        <pavadinimas> Boeing 747-8 </pavadinimas>
        <galia>8200</galia>
      </lektuvas>
      <data dienuSk="1">
        <pakilimo>2015-11-10</pakilimo>
        <nusileidimo>2015-11-11</nusileidimo>
      </data>
      <laikas>
        <pakilimo>11:40</pakilimo>
        <nusileidimo>11:40</nusileidimo>
      </laikas>
      <trukme>1440</trukme>
    </skrydis>
  </OroUostas>
  <OroUostas pavadinimas ="Kauno oro uostas" kodas = "KUN" >
    <skrydis>
      <bendrove>Ukraine international airlines</bendrove>
      <tikslas pavadinimas="Kievas" kodas = "KBP"/>
      <kaina>
        <Eur>50</Eur>
        <Lt>172.5</Lt>
      </kaina>
      <lektuvas vietos="100">
        <pavadinimas> AIRBUS A200 </pavadinimas>
        <galia>8200</galia>
      </lektuvas>
      <data>
        <pakilimo>2015-10-12</pakilimo>
        <nusileidimo>2015-10-12</nusileidimo>
      </data>
      <laikas>
        <pakilimo>20:00</pakilimo>
        <nusileidimo>22:00</nusileidimo>
      </laikas>
      <trukme>120</trukme>
    </skrydis>
  </OroUostas>
  <OroUostas pavadinimas ="Kievas" kodas = "KBP" />
  <OroUostas pavadinimas ="Copenhagen Airport" kodas = "CPH" />
  <OroUostas pavadinimas ="John F. Kennedy Airport" kodas = "JFK" />
  <OroUostas pavadinimas ="London Stansted Airport" kodas = "STD" />
</OroUostai>
